version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: path-planner
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"